import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Menu from "@/components/MenuLateral/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          h-screen flex
        `}
      >
        <div
          className="w-[300px] flex flex-col items-center pt-10"
          style={{
            boxShadow: "2px 0 3px rgba(0, 0, 0, .4)"
          }}
        >
          <img src="/logo.png" className="w-[70%]" alt="Logo" />
          <Menu />
        </div>

        <div className="p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
